// Social preview test for OG and Twitter tags validation
import { JSDOM } from 'jsdom';

// Mock HTML that would be generated by SSR server
function generateMockSsrHtml(matchId: string): string {
  return `<!doctype html>
  <html lang="en">
    <head>
      <meta charset="utf-8"/>
      <meta name="viewport" content="width=device-width,initial-scale=1"/>
      <title>Match ${matchId} | Crickzen</title>
      <meta name="description" content="Live score, squads and updates for match ${matchId} on Crickzen."/>
      <link rel="canonical" href="https://www.crickzen.com/match/${matchId}"/>
      <meta property="og:title" content="Match ${matchId} | Crickzen"/>
      <meta property="og:description" content="Live score, squads and updates for match ${matchId} on Crickzen."/>
      <meta property="og:image" content="https://www.crickzen.com/images/og/matches/${matchId}.png"/>
      <meta property="og:url" content="https://www.crickzen.com/match/${matchId}"/>
      <meta property="og:type" content="website"/>
      <meta name="twitter:card" content="summary_large_image"/>
      <meta name="twitter:title" content="Match ${matchId} | Crickzen"/>
      <meta name="twitter:description" content="Live score, squads and updates for match ${matchId} on Crickzen."/>
      <meta name="twitter:image" content="https://www.crickzen.com/images/og/matches/${matchId}.png"/>
      <script type="application/ld+json">{"@context":"https://schema.org","@type":"SportsEvent","name":"Match ${matchId}"}</script>
    </head>
    <body>
      <div id="app">SSR content for match ${matchId}</div>
    </body>
  </html>`;
}

describe('Social preview meta tags', () => {
  let dom: JSDOM;
  let document: Document;
  const testMatchId = 'ipl-2023-mi-vs-csk-t20-2023-05-29';

  beforeEach(() => {
    const html = generateMockSsrHtml(testMatchId);
    dom = new JSDOM(html);
    document = dom.window.document;
  });

  afterEach(() => {
    dom.window.close();
  });

  it('contains required Open Graph tags for Facebook sharing', () => {
    const ogTitle = document.querySelector('meta[property="og:title"]') as HTMLMetaElement;
    const ogDescription = document.querySelector('meta[property="og:description"]') as HTMLMetaElement;
    const ogImage = document.querySelector('meta[property="og:image"]') as HTMLMetaElement;
    const ogUrl = document.querySelector('meta[property="og:url"]') as HTMLMetaElement;
    
    expect(ogTitle).toBeTruthy();
    expect(ogTitle.content).toContain('Crickzen');
    
    expect(ogDescription).toBeTruthy();
    expect(ogDescription.content.length).toBeGreaterThan(50);
    expect(ogDescription.content.length).toBeLessThan(160);
    
    expect(ogImage).toBeTruthy();
    expect(ogImage.content).toContain('https://www.crickzen.com/images/og/');
    expect(ogImage.content).toContain('.png');
    
    expect(ogUrl).toBeTruthy();
    expect(ogUrl.content).toContain('https://www.crickzen.com');
  });

  it('contains required Twitter Card tags', () => {
    const twitterCard = document.querySelector('meta[name="twitter:card"]') as HTMLMetaElement;
    const twitterTitle = document.querySelector('meta[name="twitter:title"]') as HTMLMetaElement;
    const twitterDescription = document.querySelector('meta[name="twitter:description"]') as HTMLMetaElement;
    const twitterImage = document.querySelector('meta[name="twitter:image"]') as HTMLMetaElement;
    
    expect(twitterCard).toBeTruthy();
    expect(twitterCard.content).toBe('summary_large_image');
    
    expect(twitterTitle).toBeTruthy();
    expect(twitterTitle.content).toContain('Crickzen');
    
    expect(twitterDescription).toBeTruthy();
    expect(twitterDescription.content.length).toBeGreaterThan(50);
    
    expect(twitterImage).toBeTruthy();
    expect(twitterImage.content).toContain('https://www.crickzen.com/images/og/');
  });

  it('has proper image dimensions for social sharing (1200x630)', () => {
    const ogImage = document.querySelector('meta[property="og:image"]') as HTMLMetaElement;
    
    // In a real implementation, you might also have width and height meta tags
    const ogImageWidth = document.querySelector('meta[property="og:image:width"]') as HTMLMetaElement;
    const ogImageHeight = document.querySelector('meta[property="og:image:height"]') as HTMLMetaElement;
    
    expect(ogImage.content).toBeTruthy();
    
    // If width/height meta tags exist, validate them
    if (ogImageWidth) {
      expect(ogImageWidth.content).toBe('1200');
    }
    if (ogImageHeight) {
      expect(ogImageHeight.content).toBe('630');
    }
  });

  it('has valid structured data for rich results', () => {
    const jsonLdScript = document.querySelector('script[type="application/ld+json"]') as HTMLScriptElement;
    
    expect(jsonLdScript).toBeTruthy();
    
    const structuredData = JSON.parse(jsonLdScript.innerHTML);
    expect(structuredData['@context']).toBe('https://schema.org');
    expect(structuredData['@type']).toBe('SportsEvent');
    expect(structuredData.name).toBeTruthy();
  });

  it('has proper canonical URL', () => {
    const canonicalLink = document.querySelector('link[rel="canonical"]') as HTMLLinkElement;
    
    expect(canonicalLink).toBeTruthy();
    expect(canonicalLink.href).toContain('https://www.crickzen.com');
    expect(canonicalLink.href).toContain(testMatchId);
  });

  it('has appropriate meta description for SEO', () => {
    const metaDescription = document.querySelector('meta[name="description"]') as HTMLMetaElement;
    
    expect(metaDescription).toBeTruthy();
    expect(metaDescription.content).toContain('Live score');
    expect(metaDescription.content.length).toBeGreaterThan(120);
    expect(metaDescription.content.length).toBeLessThan(160);
  });

  it('has responsive viewport meta tag', () => {
    const viewport = document.querySelector('meta[name="viewport"]') as HTMLMetaElement;
    
    expect(viewport).toBeTruthy();
    expect(viewport.content).toContain('width=device-width');
    expect(viewport.content).toContain('initial-scale=1');
  });

  // Test social sharing URL generation
  it('generates valid social sharing URLs', () => {
    const pageUrl = 'https://www.crickzen.com/match/' + testMatchId;
    const pageTitle = 'Match ' + testMatchId + ' | Crickzen';
    
    // Test Facebook sharing URL
    const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(pageUrl)}`;
    expect(facebookUrl).toContain('facebook.com/sharer');
    
    // Test Twitter sharing URL
    const twitterUrl = `https://twitter.com/intent/tweet?url=${encodeURIComponent(pageUrl)}&text=${encodeURIComponent(pageTitle)}`;
    expect(twitterUrl).toContain('twitter.com/intent/tweet');
    
    // Test WhatsApp sharing URL
    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(pageTitle + ' ' + pageUrl)}`;
    expect(whatsappUrl).toContain('wa.me');
  });

  // Test that all required meta tags are present for major social platforms
  it('passes social media validator requirements', () => {
    const requiredMetaTags = [
      { selector: 'meta[property="og:title"]', platform: 'Facebook/LinkedIn' },
      { selector: 'meta[property="og:description"]', platform: 'Facebook/LinkedIn' },
      { selector: 'meta[property="og:image"]', platform: 'Facebook/LinkedIn' },
      { selector: 'meta[property="og:url"]', platform: 'Facebook/LinkedIn' },
      { selector: 'meta[name="twitter:card"]', platform: 'Twitter' },
      { selector: 'link[rel="canonical"]', platform: 'SEO' },
      { selector: 'meta[name="description"]', platform: 'SEO' }
    ];

    requiredMetaTags.forEach(({ selector, platform }) => {
      const element = document.querySelector(selector);
      expect(element).toBeTruthy(`Missing ${selector} for ${platform}`);
      
      if (element instanceof HTMLMetaElement) {
        expect(element.content).toBeTruthy(`Empty content in ${selector} for ${platform}`);
      }
    });
  });
});
